name: Pipeline

on:
  push:
    paths:
      - '!docs/**'
    tags:
      - '*'
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize, labeled]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  test:
    steps:
      - name: Checkout
        uses: actions/checkout@v3

  build_and_publish_inventory:
    needs: test
    if: "github.event.release.published"
    runs-on: golang:1.19.4
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Final
        run: echo "Hello World"